services:
  db:
    image: mongo:latest
    container_name: doc-gen_db
    volumes:
      - ./db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - doc-gen_mase-group_network
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always

  fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc-gen_fe
    ports:
      - "3000:3000"                # ← internal only; nginx & cloudflared reach it
    env_file:
      - ./.env.local
    depends_on:
      - db
    networks:
      - doc-gen_mase-group_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: doc-gen_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - doc-gen_mase-group_network
    # host ports only if you want local browsing:
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - fe
    restart: unless-stopped

    

  cloudflared:
    container_name: doc-gen_cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    # Add --protocol http2 to the command:
    command: tunnel --no-autoupdate --protocol http2 run --token ${TUNNEL_TOKEN}
    env_file: ./.env
    depends_on:
      - fe
      - nginx
    networks:
      - doc-gen_mase-group_network
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    env_file: ./.env
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - db
    networks:
      - doc-gen_mase-group_network
    restart: unless-stopped

  # adminmongo:
  #   image: mrvautin/adminmongo
  #   container_name: admin-mongo
  #   ports:
  #     - "1234:1234"
  #   env_file: ./.env
  #   environment:
  #     CONN_NAME: LocalMongo
  #     DB_HOST: db
  #     DB_PORT: ${MONGO_DB_PORT}
  #     DB_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     DB_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     DB_AUTH_DATABASE: admin
  #   depends_on:
  #     - db
  #   networks:
  #     - doc-gen_mase-group_network
  #   restart: unless-stopped

networks:
  doc-gen_mase-group_network:
    driver: bridge
